import { Router } from "express";
import validate from "../middlewares/validate.middleware";
import { 
    verifyFirebaseTokenSchema, 
    firebaseResetPasswordSchema,
    sendEmailOtpSchema,
    verifyEmailOtpSchema,
    sendForgotPasswordOtpSchema,
    resetForgotPasswordSchema
} from "../validations/otp.validation";
import { 
    verifyFirebaseToken, 
    resetPassword,
    sendEmailOTP,
    verifyEmailOTP,
    sendForgotPasswordOTP,
    verifyForgotPasswordOTP,
    resetForgotPassword
} from "../controllers/otpController";
import { otpLimiter } from "../middlewares/rateLimiter";

const router = Router();

/**
 * @description Verify a Firebase ID Token generated by the mobile app (SMS Verification)
 * @access Public
 */
router.route("/verify").post(validate(verifyFirebaseTokenSchema), verifyFirebaseToken);

/**
 * @description Reset a forgotten password using a verified Firebase ID Token
 * @access Public
 */
router.route("/reset-password").post(validate(firebaseResetPasswordSchema), resetPassword);

/**
 * @description Generate, store, and dispatch a 6-digit OTP verification code to a user's email address
 * @access Public
 */
router.route("/send-email-otp").post(otpLimiter, validate(sendEmailOtpSchema), sendEmailOTP);

/**
 * @description Validate the 6-digit OTP code sent to the user's email address
 * @access Public
 */
router.route("/verify-email-otp").post(validate(verifyEmailOtpSchema), verifyEmailOTP);

/**
 * @description Send an OTP code to a registered email for password recovery
 * @access Public
 */
router.route("/forgot-password/send-otp").post(otpLimiter, validate(sendForgotPasswordOtpSchema), sendForgotPasswordOTP);

/**
 * @description Validate the 6-digit OTP code sent for forgot password
 * @access Public
 */
router.route("/forgot-password/verify-otp").post(validate(verifyEmailOtpSchema), verifyForgotPasswordOTP);

/**
 * @description Reset a forgotten password using a verified email OTP code
 * @access Public
 */
router.route("/forgot-password/reset").post(validate(resetForgotPasswordSchema), resetForgotPassword);

export default router;
