import { Router } from "express";
import validate from "../middlewares/validate.middleware";
import { 
    verifyFirebaseTokenSchema, 
    firebaseResetPasswordSchema,
    sendEmailOtpSchema,
    verifyEmailOtpSchema
} from "../validations/otp.validation";
import { 
    verifyFirebaseToken, 
    resetPassword,
    sendEmailOTP,
    verifyEmailOTP
} from "../controllers/otpController";

const router = Router();

/**
 * @description Verify a Firebase ID Token generated by the mobile app (SMS Verification)
 * @access Public
 */
router.route("/verify").post(validate(verifyFirebaseTokenSchema), verifyFirebaseToken);

/**
 * @description Reset a forgotten password using a verified Firebase ID Token
 * @access Public
 */
router.route("/reset-password").post(validate(firebaseResetPasswordSchema), resetPassword);

/**
 * @description Generate, store, and dispatch a 6-digit OTP verification code to a user's email address
 * @access Public
 */
router.route("/send-email-otp").post(validate(sendEmailOtpSchema), sendEmailOTP);

/**
 * @description Validate the 6-digit OTP code sent to the user's email address
 * @access Public
 */
router.route("/verify-email-otp").post(validate(verifyEmailOtpSchema), verifyEmailOTP);

export default router;
