import { Router } from "express";
import validate from "../middlewares/validate.middleware";
import { verifyFirebaseTokenSchema, firebaseResetPasswordSchema } from "../validations/otp.validation";
import { verifyFirebaseToken, resetPassword } from "../controllers/otpController";

const router = Router();

/**
 * @description Verify a Firebase ID Token generated by the mobile app
 * @access Public
 */
router.route("/verify").post(validate(verifyFirebaseTokenSchema), verifyFirebaseToken);

/**
 * @description Reset a forgotten password using a verified Firebase ID Token
 * @access Public
 */
router.route("/reset-password").post(validate(firebaseResetPasswordSchema), resetPassword);

export default router;
