import { Request, Response } from "express";
import admin from "../config/firebase";
import User from "../models/User";
import Worker from "../models/Workers";
import EmailOTP from "../models/EmailOTP";
import { sendOTPEmail } from "../services/emailService";

/**
 * @description Verify a Firebase ID Token generated by the mobile app after SMS verification
 * @route POST /api/v1/auth/otp/verify
 * @access Public
 */
export const verifyFirebaseToken = async (req: Request, res: Response) => {
    try {
        const { idToken, type } = req.body;

        if (!admin.apps.length) {
            res.status(500).json({ success: false, message: "Firebase is not configured on the server." });
            return;
        }

        // Decode the token with Firebase Admin
        const decodedToken = await admin.auth().verifyIdToken(idToken);
        const phoneNumber = decodedToken.phone_number; // Format: +1234567890

        if (!phoneNumber) {
            res.status(400).json({ success: false, message: "No phone number attached to this Firebase token" });
            return;
        }

        // Optionally check if the user exists in our DB
        const Model = type === 'worker' ? Worker : User;
        
        // We match by phone. NOTE: phoneNumber from firebase includes country code (+92...)
        // Ensure your frontend passes phone numbers to our backend in the exact same format!
        const account = await Model.findOne({ phone: phoneNumber });

        res.status(200).json({
            success: true,
            message: "Phone number verified successfully",
            data: {
                phoneNumber,
                accountExists: !!account
            }
        });

    } catch (error: any) {
        console.error("Firebase Verification Error:", error);
        res.status(401).json({ success: false, message: "Invalid or expired Firebase ID token" });
    }
};

/**
 * @description Reset Password using Firebase ID Token
 * @route POST /api/v1/auth/otp/reset-password
 * @access Public
 */
export const resetPassword = async (req: Request, res: Response) => {
    try {
        const { idToken, newPassword, type } = req.body;

        if (!admin.apps.length) {
            res.status(500).json({ success: false, message: "Firebase is not configured on the server." });
            return;
        }

        // 1. Verify Token
        const decodedToken = await admin.auth().verifyIdToken(idToken);
        const phoneNumber = decodedToken.phone_number;

        if (!phoneNumber) {
            res.status(400).json({ success: false, message: "No phone number attached to this Firebase token" });
            return;
        }

        // 2. Find Account
        const Model = type === 'worker' ? Worker : User;
        const account = await Model.findOne({ phone: phoneNumber });

        if (!account) {
            res.status(404).json({ success: false, message: `Account not found for phone number: ${phoneNumber}` });
            return;
        }

        // 3. Apply new password
        account.password = newPassword;
        await account.save();

        res.status(200).json({
            success: true,
            message: "Password reset successful. You can now login with your new password."
        });

    } catch (error: any) {
        console.error("Firebase Reset Password Error:", error);
        res.status(401).json({ success: false, message: "Invalid or expired Firebase ID token" });
    }
};

/**
 * @description Generate, store and send a 6-digit OTP to the user's email address
 * @route POST /api/v1/otp/send-email-otp
 * @access Public
 */
export const sendEmailOTP = async (req: Request, res: Response): Promise<void> => {
    try {
        const { email } = req.body;

        if (!email) {
            res.status(400).json({ success: false, message: "Email address is required" });
            return;
        }

        const normalizedEmail = email.trim().toLowerCase();

        // 1. Check if user already exists with this email address
        const existedUser = await User.findOne({ email: normalizedEmail });
        const existedWorker = await Worker.findOne({ email: normalizedEmail });
        if (existedUser || existedWorker) {
            res.status(409).json({ success: false, message: "Email is already in use by another account" });
            return;
        }

        // 2. Generate a random 6-digit verification code
        const otpCode = Math.floor(100000 + Math.random() * 900000).toString();

        // 3. Set expiration time to 10 minutes from now
        const expiresAt = new Date(Date.now() + 10 * 60 * 1000);

        // 4. Remove any existing pending OTPs for this email address to avoid conflicts
        await EmailOTP.deleteMany({ email: normalizedEmail });

        // 5. Save the new OTP record to the database
        await EmailOTP.create({
            email: normalizedEmail,
            code: otpCode,
            expiresAt
        });

        // 6. Send the OTP email via Resend
        const { data, error } = await sendOTPEmail(normalizedEmail, otpCode);

        if (error) {
            console.error("Resend API failed to dispatch OTP email:", error);
            res.status(500).json({ 
                success: false, 
                message: "Failed to send verification email. Please try again later." 
            });
            return;
        }

        res.status(200).json({
            success: true,
            message: "Verification code sent to your email address successfully"
        });

    } catch (error: any) {
        console.error("sendEmailOTP Error:", error);
        res.status(500).json({ success: false, message: "An internal server error occurred while sending the code" });
    }
};

/**
 * @description Verify the 6-digit OTP code sent to the user's email address
 * @route POST /api/v1/otp/verify-email-otp
 * @access Public
 */
export const verifyEmailOTP = async (req: Request, res: Response): Promise<void> => {
    try {
        const { email, code } = req.body;

        if (!email || !code) {
            res.status(400).json({ success: false, message: "Email address and verification code are required" });
            return;
        }

        const normalizedEmail = email.trim().toLowerCase();
        const cleanedCode = code.trim();

        // 1. Find the active OTP document matching email and code
        const otpRecord = await EmailOTP.findOne({ 
            email: normalizedEmail, 
            code: cleanedCode 
        });

        if (!otpRecord) {
            res.status(400).json({ 
                success: false, 
                message: "Invalid or expired verification code" 
            });
            return;
        }

        // 2. Code is correct! Delete the OTP record so it can't be reused
        await EmailOTP.deleteOne({ _id: otpRecord._id });

        res.status(200).json({
            success: true,
            message: "Email address verified successfully. You can now continue your registration."
        });

    } catch (error: any) {
        console.error("verifyEmailOTP Error:", error);
        res.status(500).json({ success: false, message: "An internal server error occurred during verification" });
    }
};

/**
 * @description Generate, store, and send a 6-digit OTP to a registered user/worker email for password reset
 * @route POST /api/v1/otp/forgot-password/send-otp
 * @access Public
 */
export const sendForgotPasswordOTP = async (req: Request, res: Response): Promise<void> => {
    try {
        const { email, type } = req.body;
        const accountType = type || 'user';

        if (!email) {
            res.status(400).json({ success: false, message: "Email address is required" });
            return;
        }

        const normalizedEmail = email.trim().toLowerCase();

        // 1. Verify the account exists
        const Model = accountType === 'worker' ? Worker : User;
        const account = await Model.findOne({ email: normalizedEmail });

        if (!account) {
            res.status(404).json({ 
                success: false, 
                message: `No active ${accountType} account found with that email address.` 
            });
            return;
        }

        // 2. Generate a random 6-digit verification code
        const otpCode = Math.floor(100000 + Math.random() * 900000).toString();

        // 3. Set expiration time to 10 minutes from now
        const expiresAt = new Date(Date.now() + 10 * 60 * 1000);

        // 4. Remove any existing pending OTPs for this email address to avoid conflicts
        await EmailOTP.deleteMany({ email: normalizedEmail });

        // 5. Save the new OTP record to the database
        await EmailOTP.create({
            email: normalizedEmail,
            code: otpCode,
            expiresAt
        });

        // 6. Send the OTP email via Resend
        const { error } = await sendOTPEmail(normalizedEmail, otpCode);

        if (error) {
            console.error("Resend API failed to dispatch forgot-password OTP email:", error);
            res.status(500).json({ 
                success: false, 
                message: "Failed to send reset email. Please try again later." 
            });
            return;
        }

        res.status(200).json({
            success: true,
            message: "Password reset code sent to your email address successfully"
        });

    } catch (error: any) {
        console.error("sendForgotPasswordOTP Error:", error);
        res.status(500).json({ success: false, message: "An internal server error occurred while sending the code" });
    }
};

/**
 * @description Validate the 6-digit OTP code sent for forgot password
 * @route POST /api/v1/otp/forgot-password/verify-otp
 * @access Public
 */
export const verifyForgotPasswordOTP = async (req: Request, res: Response): Promise<void> => {
    try {
        const { email, code } = req.body;

        if (!email || !code) {
            res.status(400).json({ success: false, message: "Email address and verification code are required" });
            return;
        }

        const normalizedEmail = email.trim().toLowerCase();
        const cleanedCode = code.trim();

        // 1. Find the active OTP document matching email and code
        const otpRecord = await EmailOTP.findOne({ 
            email: normalizedEmail, 
            code: cleanedCode 
        });

        if (!otpRecord) {
            res.status(400).json({ 
                success: false, 
                message: "Invalid or expired verification code" 
            });
            return;
        }

        res.status(200).json({
            success: true,
            message: "Code verified successfully. You can now reset your password."
        });

    } catch (error: any) {
        console.error("verifyForgotPasswordOTP Error:", error);
        res.status(500).json({ success: false, message: "An internal server error occurred during verification" });
    }
};

/**
 * @description Reset Password using a verified Email OTP code
 * @route POST /api/v1/otp/forgot-password/reset
 * @access Public
 */
export const resetForgotPassword = async (req: Request, res: Response): Promise<void> => {
    try {
        const { email, code, newPassword, type } = req.body;
        const accountType = type || 'user';

        if (!email || !code || !newPassword) {
            res.status(400).json({ success: false, message: "Email, code, and new password are required" });
            return;
        }

        const normalizedEmail = email.trim().toLowerCase();
        const cleanedCode = code.trim();

        // 1. Verify OTP code
        const otpRecord = await EmailOTP.findOne({ 
            email: normalizedEmail, 
            code: cleanedCode 
        });

        if (!otpRecord) {
            res.status(400).json({ 
                success: false, 
                message: "Invalid or expired verification code" 
            });
            return;
        }

        // 2. Find Account
        const Model = accountType === 'worker' ? Worker : User;
        const account = await Model.findOne({ email: normalizedEmail });

        if (!account) {
            res.status(404).json({ success: false, message: `Account not found for email: ${normalizedEmail}` });
            return;
        }

        // 3. Apply and hash new password (hashing is handled by model pre-save hook)
        account.password = newPassword;
        await account.save();

        // 4. Delete the OTP record so it can't be reused
        await EmailOTP.deleteOne({ _id: otpRecord._id });

        res.status(200).json({
            success: true,
            message: "Password reset successful. You can now login with your new password."
        });

    } catch (error: any) {
        console.error("resetForgotPassword Error:", error);
        res.status(500).json({ success: false, message: "An internal server error occurred while resetting the password" });
    }
};

