import { Request, Response } from "express";
import admin from "../config/firebase";
import User from "../models/User";
import Worker from "../models/Workers";

/**
 * @description Verify a Firebase ID Token generated by the mobile app after SMS verification
 * @route POST /api/v1/auth/otp/verify
 * @access Public
 */
export const verifyFirebaseToken = async (req: Request, res: Response) => {
    try {
        const { idToken, type } = req.body;

        if (!admin.apps.length) {
            res.status(500).json({ success: false, message: "Firebase is not configured on the server." });
            return;
        }

        // Decode the token with Firebase Admin
        const decodedToken = await admin.auth().verifyIdToken(idToken);
        const phoneNumber = decodedToken.phone_number; // Format: +1234567890

        if (!phoneNumber) {
            res.status(400).json({ success: false, message: "No phone number attached to this Firebase token" });
            return;
        }

        // Optionally check if the user exists in our DB
        const Model = type === 'worker' ? Worker : User;
        
        // We match by phone. NOTE: phoneNumber from firebase includes country code (+92...)
        // Ensure your frontend passes phone numbers to our backend in the exact same format!
        const account = await Model.findOne({ phone: phoneNumber });

        res.status(200).json({
            success: true,
            message: "Phone number verified successfully",
            data: {
                phoneNumber,
                accountExists: !!account
            }
        });

    } catch (error: any) {
        console.error("Firebase Verification Error:", error);
        res.status(401).json({ success: false, message: "Invalid or expired Firebase ID token" });
    }
};

/**
 * @description Reset Password using Firebase ID Token
 * @route POST /api/v1/auth/otp/reset-password
 * @access Public
 */
export const resetPassword = async (req: Request, res: Response) => {
    try {
        const { idToken, newPassword, type } = req.body;

        if (!admin.apps.length) {
            res.status(500).json({ success: false, message: "Firebase is not configured on the server." });
            return;
        }

        // 1. Verify Token
        const decodedToken = await admin.auth().verifyIdToken(idToken);
        const phoneNumber = decodedToken.phone_number;

        if (!phoneNumber) {
            res.status(400).json({ success: false, message: "No phone number attached to this Firebase token" });
            return;
        }

        // 2. Find Account
        const Model = type === 'worker' ? Worker : User;
        const account = await Model.findOne({ phone: phoneNumber });

        if (!account) {
            res.status(404).json({ success: false, message: `Account not found for phone number: ${phoneNumber}` });
            return;
        }

        // 3. Apply new password
        account.password = newPassword;
        await account.save();

        res.status(200).json({
            success: true,
            message: "Password reset successful. You can now login with your new password."
        });

    } catch (error: any) {
        console.error("Firebase Reset Password Error:", error);
        res.status(401).json({ success: false, message: "Invalid or expired Firebase ID token" });
    }
};
